### PR TITLE
Add debug_one to FM regressor

### PR DESCRIPTION
**Pull request by nakamasato**
# why

To visualize FM regressor

# what

Added `debug_one` to FM regressor. (If this idea is ok, I'd be happy to add a similar method to other FM regressors)

# check in local

<details><summary>debug_check.py</summary>

```python
from river import datasets
from river import metrics
from river.evaluate import progressive_val_score

from river import optim
from river import compose
from river import facto
from river import optim
from river import stats


def evaluate(model):
    X_y = datasets.MovieLens100K()
    metric = metrics.MAE() + metrics.RMSE()
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)


def debug(model):
    for x, _ in datasets.MovieLens100K():
        report = model.debug_one(x)
        print(report)
        break


def split_genres(x):
    genres = x['genres'].split(', ')
    return {f'genre_{genre}': 1 / len(genres) for genre in genres}


def bin_age(x):
    if x['age'] <= 18:
        return {'age_0-18': 1}
    elif x['age'] <= 32:
        return {'age_19-32': 1}
    elif x['age'] < 55:
        return {'age_33-54': 1}
    else:
        return {'age_55-100': 1}


def debug_fm():
    fm_params = {
        'n_factors': 10,
        'weight_optimizer': optim.SGD(0.025),
        'latent_optimizer': optim.SGD(0.05),
        'sample_normalization': False,
        'l1_weight': 0.,
        'l2_weight': 0.,
        'l1_latent': 0.,
        'l2_latent': 0.,
        'intercept': 3,
        'intercept_lr': .01,
        'weight_initializer': optim.initializers.Zeros(),
        'latent_initializer': optim.initializers.Normal(mu=0., sigma=0.1, seed=73),
    }

    regressor = compose.Select('user', 'item')
    regressor += (
        compose.Select('genres') |
        compose.FuncTransformer(split_genres)
    )
    regressor += (
        compose.Select('age') |
        compose.FuncTransformer(bin_age)
    )
    regressor |= facto.FMRegressor(**fm_params)
    evaluate(regressor)
    debug(regressor)


if __name__ == '__main__':
    debug_fm()
```

</details>

```bash
debug_check.py
[25,000] MAE: 0.765552, RMSE: 0.974847 – 0:00:07.676462 – 1.18 MB
[50,000] MAE: 0.766781, RMSE: 0.974597 – 0:00:15.595336 – 1.38 MB
[75,000] MAE: 0.770419, RMSE: 0.980087 – 0:00:23.766752 – 1.59 MB
[100,000] MAE: 0.773439, RMSE: 0.984339 – 0:00:31.948554 – 1.79 MB
0. Input
--------
age: 21.00000 (float)
gender: M (str)
genres: comedy, romance (str)
item: 255 (str)
occupation: student (str)
release_date: 866764800000000000 (int)
timestamp: 874731910000000000 (int)
title: My Best Friend's Wedding (1997) (str)
user: 259 (str)
zip_code: 48823 (str)

1. Transformer union
--------------------
    1.0 Select
    ----------
    item: 255 (str)
    user: 259 (str)

    1.1 ['genres'] | split_genres
    -----------------------------
    genre_comedy: 0.50000 (float)
    genre_romance: 0.50000 (float)

    1.2 ['age'] | bin_age
    ---------------------
    age_19-32: 1 (int)

age_19-32: 1 (int)
genre_comedy: 0.50000 (float)
genre_romance: 0.50000 (float)
item: 255 (str)
user: 259 (str)

2. FMRegressor
--------------
Name                           Value      Weight     Contribution  
                   Intercept    1.00000    3.20347        3.20347  
                    user_259    1.00000    0.33731        0.33731  
               genre_romance    0.50000    0.24626        0.12313  
    genre_romance - item_255    0.50000    0.15272        0.07636  
   age_19-32 - genre_romance    0.50000    0.11660        0.05830  
    age_19-32 - genre_comedy    0.50000    0.05681        0.02841  
        age_19-32 - item_255    1.00000    0.02668        0.02668  
genre_comedy - genre_romance    0.25000    0.09134        0.02283  
                   age_19-32    1.00000   -0.00495       -0.00495  
                    item_255    1.00000   -0.02429       -0.02429  
     genre_comedy - item_255    0.50000   -0.05900       -0.02950  
    genre_romance - user_259    0.50000   -0.07442       -0.03721  
        age_19-32 - user_259    1.00000   -0.06316       -0.06316  
     genre_comedy - user_259    0.50000   -0.13236       -0.06618  
         item_255 - user_259    1.00000   -0.07201       -0.07201  
                genre_comedy    0.50000   -0.30899       -0.15449  

Prediction: 3.42470
```

### CODE REVIEW

**Comment by MaxHalford** [comment]
Very nice 🤩

It's nice that you provide a test file. But ideally you should put this into a doctest. Do you know how to do that? There's loads of examples throughout the codebase. I can also help :)

**Comment by nakamasato** [comment]
> Very nice 🤩
> 
> It's nice that you provide a test file. But ideally you should put this into a doctest. Do you know how to do that? There's loads of examples throughout the codebase. I can also help :)

Thank you for your reply and advice! I've heard of doctest. I think I can check how others work! If you can briefly summarize it or gimme good example in this repo, that'd be great though. I'll take a look at https://docs.python.org/3/library/doctest.html and try adding one.

**Comment by MaxHalford** [comment]
doctests kill two birds with one stone: they show example usage of the code, and that example is tested when running pytest. See [here](https://github.com/online-ml/river/blob/main/river/linear_model/lin_reg.py#L11) for `LinearRegression`.

**Comment by nakamasato** [comment]
@MaxHalford I've added doctest. Please take a look at it when you have time. Thank you!

**Comment by MaxHalford** [comment]
Good job, it looks great! Glad you learned something new.

**Pull request merged**
