### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by TafadzwaD**
Change "that cross-validation" to "than cross-validation" since it is a comparison between two elements

### CODE REVIEW

**Comment by smastelini** [comment]
Nice!! Thanks for the fix.

**Comment by smastelini** [comment]
Thanks for the fix, @TafadzwaD !

**Comment by TafadzwaD** [comment]
@smastelini Thanks to you and the team behind River for the wonderful work, great library!!

**Comment by MaxHalford** [comment]
Cheers @TafadzwaD :)

**Pull request merged**
