### PR TITLE
Active Learning method based on Uncertainty.

### PR DESCRIPTION
**Pull request by albertfrancajosuacosta**
Strategy of Active Learning to select instances more significative based on uncertainty.

    Version 1.0.

    Reference
    I. Zliobaite, A. Bifet, B.Pfahringer, G. Holmes. “Active Learning with Drifting Streaming Data”, IEEE Transactions on Neural Netowrks and Learning Systems, Vol.25 (1), pp.27-39, 2014.

Screenshot from 2023-02-02 19-58-38

I ran the pre-commit and they all passed, with 2 skips.

### CODE REVIEW

**Comment by MaxHalford** [comment]
Thanks for the PR! I will take a look sometime next week.

*For some reason your pre-commit removed a lot of empty lines and many files. Maybe that's normal and due to a recent version of one of our pre-commit hooks, I'll take a look too.*

**Comment by MaxHalford** [comment]
Hey @albertfrancajosuacosta, thanks for merging the `main` branch.

Could you put some effort into tidying up the docstring? I suggest taking a look at the rest of the codebase to understand what format is expected. Let me know if you need clarifications :)

**Comment by MaxHalford** [comment]
There's still a bit of tidying up to do, the docstring isn't up to standard :)

**Comment by albertfrancajosuacosta** [comment]
Edit docstring of fidex_incertainty.py and random_variable_uncertainty.py. 
Updade __init__.py to insert the new classe variable_uncertainty.py. 
Creation of new class variable_uncertainty.py.

**Comment by MaxHalford** [comment]
*(I can't review this; the unit tests are failing and the docstrings are not properly formatted)*

**Pull request closed without merging**
