### PR TITLE
correct rounding for 0.0

### LINKED ISSUE #528: Rounding error
## Versions

**river version**: master 03.03.2021, but should be relevant as of 18.03.2021
**Python version**: 3.8.8
**Operating system**: Windows 10 Pro v2004

## Describe the bug

`ValueError: math domain error` in `skmultiflow_utils.py` when trying to round 0 while drawing the tree model
## Steps/code to reproduce

```python
from river import datasets
from river import evaluate
from river import metrics
from river import tree
from river import preprocessing

dataset = datasets.TrumpApproval()
model = tree.HoeffdingAdaptiveTreeRegressor(
    grace_period=50, leaf_prediction="adaptive", model_selector_decay=0.3, seed=0
)


metric = metrics.MAE()

for x, y in datasets.TrumpApproval():

    if y < 100.0:
        y = 0.0
    else:
        y = 1.0

    model = model.learn_one(x, y)


print(model.model_description())
model.draw()
```

### PR DESCRIPTION
**Pull request by ColdTeapot273K**
fixes #528

### CODE REVIEW

**Comment by MaxHalford** [comment]
tip: if you write `fixes #529` in your description, this the issue will be automatically closed when this is merged! @smastelini @jacobmontiel for visibility

**Comment by MaxHalford** [comment]
You need to run `pre-commit run --all-files`. Also a quick doctest would be nice to have, tell me if you need help writing it.

**Comment by smastelini** [comment]
Thanks, @ColdTeapot273K for your fix. I checked and it solves the issue. Let me know if you need any assistance. I can help you write a simple test if needed.

**Comment by ColdTeapot273K** [comment]
Thanks guys, I shall try to add a doctest. Don't merge yet pls

**Comment by ColdTeapot273K** [comment]
Removed mention on "adding" digits since it doesn't, in fact, happen (see tests), and I don't think there's an easy way to do it. 

I believe it's not crucial in for the application honestly.

**Comment by smastelini** [comment]
> Removed mention on "adding" digits since it doesn't, in fact, happen (see tests), and I don't think there's an easy way to do it.

You are correct. The utility only removes digits.

**Review by smastelini — APPROVED** [review]
Thanks, @ColdTeapot273K for the last changes. The added tests are nice additions to have.

**Pull request merged**
