### PR TITLE
FIX: LOF with QuantileFilter raises IndexError

### PR DESCRIPTION
**Pull request by MarekWadinger**
This pull request resolves the issue #1329 Error combining LocalOutlierFactor with AnomalyFilter

### CODE REVIEW

**Comment by MaxHalford** [comment]
Hey there @MarekWadinger, did you see my comment?

**Comment by MarekWadinger** [comment]
Hey Max,

thank you, you are absolutely right with the default score of 0. I looked at it from the perspective of two-tailed test but that's not how QuantileFIlter and ThresholdFIlter work here.

I fixed the failing test due to stateless score_one fixture, related to issue #1331. Added some quick tests if some new way of handling the statelessness would be developed and tried to run some tests from other scorers (kept the quick one).
Interestingly, the ROC AUC score for LOF on CreditCard is very low (while being quite sluggish).

PS. Sorry for my clumsy Pull requests, still learning how to contribute properly, though the guidelines here helped a lot.

**Comment by MaxHalford** [comment]
Very cool that you added a test, I appreciate it.

You still have a little doctest issue to fix, probably a normal consequence of your change.

> PS. Sorry for my clumsy Pull requests, still learning how to contribute properly, though the guidelines here helped a lot.

Don't apologize, you're doing very well ;)

**Comment by MarekWadinger** [comment]
Hmm, there's something weird going on with the failed test. It reports that the expected value is the one prior to this commit f33e3ca3fc48e5a68efd6d278e7aa3c0e4416bd0. However, there's already a new value. 

Am I missing something?

```
________________ [doctest] river.anomaly.lof.LocalOutlierFactor ________________
[gw1] darwin -- Python 3.11.5 /Users/runner/.venv/bin/python3.11
214     >>> for x, _ in datasets.CreditCard().take(200):
215     ...     lof.learn_one(x)
216 
217     >>> lof.learn_many(cc_df[201:401])
218 
219     >>> scores = []
220     >>> for x in cc_df[0][401:406]:
221     ...     scores.append(lof.score_one(x))
222 
223     >>> [round(score, 3) for score in scores]
Expected:
    [1.802, 1.937, 1.567, 1.181, 1.28]
Got:
    [1.802, 1.936, 1.566, 1.181, 1.272]

/Users/runner/work/river/river/river/anomaly/lof.py:223: DocTestFailure
```

**Comment by smastelini** [comment]
Hi @MarekWadinger. Did you update the docstring test? As you fixed bugs in the code, it expected that the outputs will change. So you will need to update that accordingly :)

**Comment by MaxHalford** [comment]
You're right @MarekWadinger, there's a bug in CI whereby the old code is being used to run the tests. I will take a look tonight to fix this. In the meantime, let's merge your PR :)

**Pull request merged**
