### PR TITLE
Rename sample_weight to w (code quality)

### PR DESCRIPTION
**Pull request by mariliatd**
Hi,

This PR is related to issue #1418.

### CODE REVIEW

**Review by MaxHalford — CHANGES_REQUESTED** [review]
Great!

Can you add a note to `unreleased.md`? This is a breaking change so it's important to list it in the release notes.

**Comment by mariliatd** [comment]
Notes added to` unreleased.md` :)

**Comment by hoanganhngo610** [comment]
@mariliatd Thank you very much for making the changes! I don't have anything to add, so it now is all comes down to @MaxHalford to finalize on this PR!

**Comment by MaxHalford** [comment]
Thanks @mariliatd :)

**Pull request merged**
