### PR TITLE
Minor fixes to ARFReg

### PR DESCRIPTION
**Pull request by smastelini**
- Make the weighted vote be applied only when aggregation is `'mean'`
- Fix typo
- Update test

### CODE REVIEW

**Comment by smastelini** [comment]
Hey @jacobmontiel, just one question: shouldn't the drift detectors be updated before the base models are updated with new instances?

While reading the code, this got my attention.

**Comment by jacobmontiel** [comment]
> shouldn't the drift detectors be updated before the base models are updated with new instances?

Pinging @hmgomes

This also applies to the classifier version.

**Comment by smastelini** [comment]
@jacobmontiel, could we close this one and address the more theoretical bit in another PR, if necessary?

**Review by jacobmontiel — APPROVED** [review]
Changes are correct. Thanks @smastelini

**Comment by jacobmontiel** [comment]
Tests fail due to upstream issues. Closing the PR.

**Pull request merged**
