### PR TITLE
Twitter stream

### PR DESCRIPTION
**Pull request by MaxHalford**
There we go @Dennis1989!

I decided to not use `tweepy` to avoid having an extra dependency (other than `requests`). I implemented a client for the Twitter API v2 [filtered stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction) endpoints. I hope that's satisfactory! If not let me know.

@raphaelsty you can take a look too if you're not too busy :)

### CODE REVIEW

**Comment by gbolmier** [comment]
Nice addition! Did you think of using [`urllib.request`](https://docs.python.org/3/library/urllib.request.html) from the standard lib instead of `requests`?

**Comment by Dennis1989** [comment]
Awesome! I can work with that. Thank you for implementing this feature so quickly @MaxHalford. I will utilize this stream in a notebook example for textclust. Also, I agree that Tweepy would be a super over-the-top dependency.

**Comment by MaxHalford** [comment]
> Nice addition! Did you think of using [urllib.request](https://docs.python.org/3/library/urllib.request.html) from the standard lib instead of requests?

No I didn't, but I'll take a stab at it!

**Comment by MaxHalford** [comment]
@gbolmier I did my best and managed to get rules, delete rules, and set rules using `urlib.request`. But it's too difficult to handle a streaming response without `requests`.

For posterity:

**Get rules**

```py
import json
import urllib.request

req = urllib.request.Request(
    url='https://api.twitter.com/2/tweets/search/stream/rules',
    method='GET',
    headers={
        "Authorization": f"Bearer {bearer_token}",
        "User-Agent": "v2FilteredStreamPython",
    }
)
with urllib.request.urlopen(req) as f:
    rules = json.loads(f.read().decode())
    print(rules)
```

**Delete rules**

```py
rule_ids = [rule["id"] for rule in rules.get("data", [])]
if rule_ids:
    req = urllib.request.Request(
        url='https://api.twitter.com/2/tweets/search/stream/rules',
        method='POST',
        data=json.dumps({"delete": {"ids": rule_ids}}).encode('ascii'),
        headers={
            "Authorization": f"Bearer {bearer_token}",
            "User-Agent": "v2FilteredStreamPython",
            "Content-Type": 'application/json'
        }
    )
    with urllib.request.urlopen(req) as f:
        ...
```

**Add rules**

```py
rules = ["dog"]
req = urllib.request.Request(
    url='https://api.twitter.com/2/tweets/search/stream/rules',
    method='POST',
    data=json.dumps({"add": [{"value": rule, "tag": rule} for rule in rules]}).encode('ascii'),
    headers={
        "Authorization": f"Bearer {bearer_token}",
        "User-Agent": "v2FilteredStreamPython",
        "Content-Type": 'application/json',
    }
)
with urllib.request.urlopen(req) as f:
    ...
```

**Listening to tweets**

```py
req = urllib.request.Request(
    url='https://api.twitter.com/2/tweets/search/stream/rules',
    method='GET',
    headers={
        "Authorization": f"Bearer {bearer_token}",
        "User-Agent": "v2FilteredStreamPython",
        "Content-Type": 'application/json',
        "Transfer-Encoding": "chunked"
    }
)
with urllib.request.urlopen(req) as f:
    ...
    # ???
```

**Pull request merged**
