### PR TITLE
Introduce base.DriftAndWarningDetector

### PR DESCRIPTION
**Pull request by MaxHalford**
Some drift detectors have a `warning_detected` property, some don't. I believe introducing a new base class clarifies this difference.

### CODE REVIEW

**Comment by smastelini** [comment]
That might be helpful indeed. But keep in my mind that the input type is as important as the two level detection capabilities. I still didn't figure out a practical way to organize them in classes.

**Comment by smastelini** [comment]
Some detectors support continual entries, other only binary inputs. Most of the binary ones have warning levels.

**Review by smastelini — APPROVED** [review]

**Comment by MaxHalford** [comment]
Ah good catch @smastelini, I'll have a think about it then :)

**Comment by MaxHalford** [comment]
Ok I'm going to merge this to help with #1149, but I'll keep your comment in mind. You're right, we should distinguish between continuous and discrete drift detectors.

**Pull request merged**
