### PR TITLE
No more return self

### PR DESCRIPTION
**Pull request by mariliatd**
Hi,

This PR is related to issue #1417.

I've removed the `return self` from all the `learn_one`  and `learn_many` methods of every class. Please, let me know if I've missed something.

### CODE REVIEW

**Review by AdilZouitine — COMMENTED** [review]
LGTM, I'm waiting for another review to merge. 
Thank you :smile:

**Comment by MaxHalford** [comment]
Look good too. One thing though: could you go through the notebooks and make sure everything looks ok?

**Comment by hoanganhngo610** [comment]
@mariliatd Thank you very much, once again. I believe that after double checking, I do not see anywhere else in the notebooks that need modifying. @MaxHalford @AdilZouitine Anything else you think that needs to be changed?

**Comment by MaxHalford** [comment]
I'll take a look when I have some spare time, bare with me. This is a big change, so I prefer to have a good look by myself.

**Comment by MaxHalford** [comment]
Merging! I'm going to make a v0.21 release with this.

**Comment by mariliatd** [comment]
Thanks! :)

**Pull request merged**
