### PR TITLE
Added TCPD benchmark, BOCPD, WATCH, ECDAS methods

### PR DESCRIPTION
**Pull request by Gatorino**

### CODE REVIEW

**Comment by MaxHalford** [comment]
Hey there! Can you add some context to your pull request? There's a lot of stuff you added. Ideally, it would be better to proceed in several smaller pull requests. Maybe a first one to add datasets, and then one pull request per method you want to add.

Anyway, I think we should discuss your work in general. There seems to be a lot of good stuff, and I'd like to integrate it, but the pull request is just too big to merge in one go.

**Comment by Gatorino** [comment]
Hello ! We're a group of students of Mariam Barry's class. We worked on the changepoint detection algorithms with another group who implemented the TCPD benchmark. I reached out to the other group to discuss how to split the pull requests. Although we are all doing our internships, I think it would be good to discuss more about the details, and the other group is also available. When and how could we meet?

**Comment by MaxHalford** [comment]
I see, good stuff. I'm available all week, except on Friday. If not, most of the time next week works for me.

**Comment by Gatorino** [comment]
Would you be available tomorrow Tuesday 06/06 at 5pm Paris time?

**Comment by MaxHalford** [comment]
> Would you be available tomorrow Tuesday 06/06 at 5pm Paris time?

Yep let's do it! Send an invite to maxhalford25@gmail.com

**Comment by Gatorino** [comment]
Here is the link to the meeting ! https://meet.google.com/zag-krcz-xeu

**Comment by MaxHalford** [comment]
Apologies, I had an emergency at home. Can we postpone till tomorrow? Also, I wouldn't share links like that in public. You can send it by email to maxhalford25@gmail.com

**Comment by Gatorino** [comment]
Yes it's good for all of us, I sent the meeting link in the description of the mail notification.

**Comment by MaxHalford** [comment]
Hey can guys, can we do 4PM instead of 5PM?

**Pull request closed without merging**
