### PR TITLE
implement neat repr for TimeRolling

### PR DESCRIPTION
**Pull request by ColdTeapot273K**
Add a neat \_\_repr\_\_ for TimeRolling metric wrapper (see doctest)

Have been using it in my work for a while. 
I found it more readable than the current \_\_repr\_\_ for Rolling. If you like, I can align Rolling \_\_repr\_\_ for consistency.

### CODE REVIEW

**Comment by MaxHalford** [comment]
Good idea!

I would prefer:

```
Rolling 2 days, 0:00:00 window MAE: 0.5
```

But then it's just a question of taste. Do what feels best.

**Comment by ColdTeapot273K** [comment]
Thanks for the feedback. 
Motivation was to see metric first since it's fixed lenth, "typical" and the most valuable information and easy to eyeball. And metric parameters second because bigger length and extendability (they could have arbitrary length/contents and be extendable). 
Not like I'm overthinking, just my experience from presenting results :)

**Comment by ColdTeapot273K** [comment]
Finished.

**Comment by MaxHalford** [comment]
Can we agree on something in the middle? How about

```
MAE: 0.5 (rolling 2 days, 0:00:00)
```

**Comment by ColdTeapot273K** [comment]
Deal 🤝

**Comment by MaxHalford** [comment]
Last nit: I would prefer a single space rather than a `\t` :)

**Comment by ColdTeapot273K** [comment]
My motivation is that \t allows for more or less fixed position of the description, regardless of numbers' size.

For example, I use several metrics, which gives

w/ tabs:

```log
SMAPE: 3.41847	Metric rolling window period: 1 days 00:00:00
SMAPE: 4.087315	Metric rolling window period: 7 days 00:00:00
SMAPE: 3.803504	Metric rolling window period: 30 days 00:00:00
SMAPE: 4.251176	Metric rolling window period: 120 days 00:00:00
SMAPE: 4.806921	Metric rolling window period: 180 days 00:00:00
SMAPE: 5.215561	Metric rolling window period: 365 days 00:00:00
```

w/ spaces:

```log
SMAPE: 3.41847 Metric rolling window period: 1 days 00:00:00
SMAPE: 4.087315 Metric rolling window period: 7 days 00:00:00
SMAPE: 3.803504 Metric rolling window period: 30 days 00:00:00
SMAPE: 4.251176 Metric rolling window period: 120 days 00:00:00
SMAPE: 4.806921 Metric rolling window period: 180 days 00:00:00
SMAPE: 5.215561 Metric rolling window period: 365 days 00:00:00
```

What do you pick? Personally, I pick tabs

**Comment by MaxHalford** [comment]
You've convinced me :)

**Pull request merged**
